import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Bridgr",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="google-site-verification" content="0NpnAMXqJu5WSfRCWqvUyKntZ8AcABfjC_2kkUzNyEc" />
      </head>
      <body>
         <Navbar />
        {children}
        <ToastContainer position="top-right" autoClose={3000} />
        <Footer/>
      </body>
    </html>
  );
}
